---

- name: Run Overcloud checks
  args:
      chdir: "{{ ansible_user_dir }}/browbeat/ansible"
  shell: "ansible-playbook -i hosts check/site.yml"
  when:
      - test.overcloud.checks is defined and test.overcloud.checks
      - overcloud_checks is defined and overcloud_checks

- name: Run Browbeat performance workload
  args:
      chdir: "{{ ansible_user_dir }}/browbeat"
  shell: "source .browbeat-venv/bin/activate; python browbeat.py -s {{ browbeat_config }}"
  when:
      - test.overcloud.performance is defined and test.overcloud.performance
      - browbeat_config is defined and browbeat_config
